# Generated by Django 4.0.4 on 2022-05-28 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('mobil', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('date_create', models.DateField()),
                ('date_update', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('client_potentiel', 'CLIENT_POTENTIEL'), ('client_existant', 'CLIENT_EXISTANT')], max_length=100)),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacte_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company_name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField(auto_now=True)),
                ('event_name', models.CharField(max_length=150)),
                ('start_date_event', models.DateField()),
                ('end_date_event', models.DateField()),
                ('status', models.BooleanField(max_length=15)),
                ('amount', models.FloatField(max_length=20)),
                ('payement_due', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_customer', to='create_events.client')),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('note', models.TextField(max_length=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='create_events.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='create_events.contract')),
                ('support_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
