# Generated by Django 4.0.4 on 2022-05-22 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('contact_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacte_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company_name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField(auto_now=True)),
                ('event_name', models.CharField(max_length=150)),
                ('start_date_event', models.DateField()),
                ('end_date_event', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_customer', to='create_events.client')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='create_events.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='create_events.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contributor', to='create_events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contributor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'client', 'event')},
            },
        ),
    ]
