# Generated by Django 4.0.4 on 2022-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='statu',
            field=models.CharField(choices=[('a_venir', 'EVENEMENT A VENIR'), ('en_cours', 'EN COUR'), ('cloturer', 'CLOTURER')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
