# Generated by Django 4.0.4 on 2022-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_crm',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
